<?php

namespace App\Tests\Components\Orderflow\Communication;

use App\Components\Orderflow\Business\Validation\OrderFlowValidation;
use App\Components\Orderflow\Persistence\OrderFlowEntityManager;
use App\Components\Orderflow\Persistence\OrdersRepository;
use App\Components\Registration\Persistence\UserEntityManager;
use App\Components\ShoppingCart\Persistence\ShoppingCartEntityManager;
use App\Components\ShoppingCart\Persistence\ShoppingCartRepository;
use App\Entity\Orders;
use App\Entity\User;
use App\Global\Persistence\DTO\UserDTO;
use App\Global\Persistence\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;

class OrderFlowControllerTest extends WebTestCase
{
    public Request $request;
    public EntityManagerInterface $entityManager;
    public OrderFlowValidation $flowValidation;
    public ShoppingCartRepository $cartRepository;
    public  ShoppingCartEntityManager $cartEntityManager;
    public UserRepository $userRepository;
    public function setUp(): void
    {
        $this->request = $this->createMock(Request::class);
        $this->entityManager = $this->createMock(EntityManagerInterface::class);
        $this->flowValidation = $this->createMock(OrderFlowValidation::class);
        $this->cartRepository = $this->createMock(ShoppingCartRepository::class);
        $this->cartEntityManager = $this->createMock(ShoppingCartEntityManager::class);
        $this->userRepository = $this->createMock(UserRepository::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndexUserNoPOST()
    {
        $client = static::createClient();

        $userRepo = static::getContainer()->get(UserRepository::class);
        $user = $userRepo->findOneByEmail('test@lol.com');
        $client->loginUser($user);

        $client->request('GET', '/order/flow');

        self::assertResponseIsSuccessful($client->getResponse()->getContent());
        self::assertNotEmpty($client->getResponse()->getContent());
    }

    public function testIndexWithUserNotFoundNoPOST()
    {
        $client = static::createClient();

        // Make a GET request to /order/flow
        $client->request('GET', '/order/flow');

        // Check if the response is a 404 Not Found (HTTP status code 404)
        self::assertResponseStatusCodeSame(Response::HTTP_NOT_FOUND);
        $this->assertStringContainsString('User not authenticated.', $client->getResponse()->getContent());
    }

    public function testIndexWhenResponseIsNull()
    {
        $entityManagerMock = $this->createMock(OrderFlowEntityManager::class);
        $entityManagerMock->expects($this->once())->method('persistOrder')->willReturn(null);

        $client = static::createClient();
        $client->getContainer()->set(OrderFlowEntityManager::class, $entityManagerMock);

        $userRepo = static::getContainer()->get(UserRepository::class);
        $user = $userRepo->findOneByEmail('test@lol.com');
        $client->loginUser($user);

        $client->request('POST', '/order/flow');

        self::assertResponseRedirects('/order/flow/thankyou');
    }

    public function testSuccessNoUser()
    {
        $client = static::createClient();

        // Make a GET request to /order/flow
        $client->request('GET', '/order/flow/thankyou');

        // Check if the response is a 404 Not Found (HTTP status code 404)
        self::assertResponseStatusCodeSame(Response::HTTP_NOT_FOUND);
        $this->assertStringContainsString('User not authenticated.', $client->getResponse()->getContent());
    }

    public function testSuccessNoOrderFound()
    {
        $client = static::createClient();

        $userRepo = static::getContainer()->get(UserRepository::class);
        $user = $userRepo->findOneByEmail('test@lol.com');
        $client->loginUser($user);

        $client->request('POST', '/order/flow/thankyou');
        self::assertResponseStatusCodeSame(Response::HTTP_NOT_FOUND);
        $this->assertStringContainsString('Order not found.', $client->getResponse()->getContent());
    }

    public function testSuccess()
    {
        $order = new Orders();

        $ordersRepository = $this->createMock(OrdersRepository::class);
        $ordersRepository->expects($this->once())->method('findMostRecentOrderByEmail')->willReturn($order);

        $client = static::createClient();
        $client->getContainer()->set(OrdersRepository::class, $ordersRepository);

        $userRepo = static::getContainer()->get(UserRepository::class);
        $user = $userRepo->findOneByEmail('test@lol.com');
        $client->loginUser($user);

        $client->request('POST', '/order/flow/thankyou');

        self::assertStringNotContainsString('User not authenticated.', $client->getResponse()->getContent());
        self::assertStringNotContainsString('Order not found.', $client->getResponse()->getContent());
        self::assertResponseIsSuccessful($client->getResponse()->getContent());
        self::assertStringContainsString('Products purchased', $client->getResponse()->getContent());
    }
}
