<?php
declare(strict_types=1);

namespace App\Tests\Unit\Components\Orderflow;

use Monolog\Test\TestCase;

class OrderFlowBusinessFacadeTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testFindOneByEmail() : void
    {

    }
}