<?php
declare(strict_types=1);

namespace App\Tests\Integration\Components\Homepage;

use App\Components\Homepage\Business\HomepageBusinessFacade;
use App\Global\Persistence\API\ItemsTransferService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class HomepageBusinessFacadeTest extends KernelTestCase
{
    private readonly HomepageBusinessFacade $homepageBusinessFacade;
    private readonly ItemsTransferService $itemsTransferService;

    protected function setUp(): void
    {
        $this->itemsTransferService = self::getContainer()->get(ItemsTransferService::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        $entityManager = self::getContainer()->get(EntityManagerInterface::class);
        $connection = $entityManager->getConnection();
        $connection->executeQuery('DELETE FROM items');
        $connection->executeQuery('ALTER TABLE items AUTO_INCREMENT=0');
        $connection->close();
        parent::tearDown();
    }

    public function testItemTransferNoCache(): void
    {
        $this->homepageBusinessFacade = new HomepageBusinessFacade($this->itemsTransferService);

        $res = $this->homepageBusinessFacade->itemTransfer('4');

        self::assertSame(334, $res[0]->itemId);
        self::assertSame(9389, $res[1]->itemId);

        self::assertSame('Switzerland', $res[0]->nationality);
        self::assertSame('Germany', $res[1]->nationality);
    }
}