# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    App\Global\Service\Stripe\StripeClient:
        arguments:
            $apiKey: '%stripe_secret_key%'
    App\Service\API\ItemsTransferService:
        class: 'App\Global\Persistence\API\ItemsTransferService'
        arguments:
            $itemRepository: '@App\Model\Repository\ItemRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $client: '@http_client'
    security.authentication.manager:
        class: Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface
        public: false
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
