<?php

namespace App\Tests\Components\Registration\Communication;

use App\Components\Registration\Business\Validation\UserRegistrationValidation;
use App\Components\Registration\Communication\RegistrationController;
use App\Components\Registration\Persistence\UserEntityManager;
use App\Global\Persistence\DTO\UserDTO;
use App\Global\Persistence\Mapping\Mapper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class RegistrationControllerTest extends WebTestCase
{
    private EntityManagerInterface $entityManager;
    public function setUp(): void
    {
        $this->entityManager = $this->createMock(EntityManagerInterface::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRegisterInvalid() : void
    {
        // Create a Symfony test client
        $client = static::createClient();
        $client->request('POST', '/register');

        self::assertStringContainsString('Oops, your name doesn&#039;t look right', $client->getResponse()->getContent());
        self::assertStringContainsString('Oops, your email doesn&#039;t look right', $client->getResponse()->getContent());
        self::assertStringContainsString('Oops, your password doesn&#039;t look right', $client->getResponse()->getContent());
    }
    public function testRegisterValid() : void
    {
        // Create a Symfony test client
        $client = static::createClient();

        // Create a valid user registration request with form data
        $client->request('POST', '/register', [
            'username' => 'ValidUsername',
            'email' => 'valid@example.com',
            'password' => 'ValidPassword123!',
        ]);

        self::assertStringNotContainsString('Oops, your name doesn&#039;t look right', $client->getResponse()->getContent());
        self::assertStringNotContainsString('Oops, your email doesn&#039;t look right', $client->getResponse()->getContent());
        self::assertStringNotContainsString('Oops, your password doesn&#039;t look right', $client->getResponse()->getContent());
    }
}
