<?php

namespace App\Tests\Service\Mapping;

use App\Service\Mapping\Mapper;
use Monolog\Test\TestCase;

class MapperTest extends TestCase
{
    private Mapper $mapper;
    public function setUp(): void
    {
        $this->mapper = new Mapper();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testMapItems()
    {
    }
}